CREATE DATABASE IF NOT EXISTS healthcare_db;
USE healthcare_db;

CREATE TABLE IF NOT EXISTS PATIENT (
  Patient_ID INT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Gender VARCHAR(20),
  DOB DATE,
  Age INT,
  Blood_Group VARCHAR(10),
  Address TEXT,
  City VARCHAR(100),
  State VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS PATIENT_PHONE (
  Patient_ID INT NOT NULL,
  Phone_Number VARCHAR(20) NOT NULL,
  PRIMARY KEY (Patient_ID, Phone_Number),
  FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DOCTOR (
  Doctor_ID INT PRIMARY KEY,
  Name VARCHAR(100) NOT NULL,
  Specialty VARCHAR(100),
  Contact VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS CLINIC (
  Clinic_ID INT PRIMARY KEY,
  Clinic_Name VARCHAR(100) NOT NULL,
  Location VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS VISIT (
  Visit_ID INT PRIMARY KEY,
  Visit_Date DATE NOT NULL,
  Patient_ID INT NOT NULL,
  Doctor_ID INT,
  Clinic_ID INT,
  FOREIGN KEY (Patient_ID) REFERENCES PATIENT(Patient_ID) ON DELETE CASCADE,
  FOREIGN KEY (Doctor_ID) REFERENCES DOCTOR(Doctor_ID) ON DELETE SET NULL,
  FOREIGN KEY (Clinic_ID) REFERENCES CLINIC(Clinic_ID) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS VISIT_SYMPTOMS (
  Visit_ID INT NOT NULL,
  Symptoms VARCHAR(255) NOT NULL,
  PRIMARY KEY (Visit_ID, Symptoms),
  FOREIGN KEY (Visit_ID) REFERENCES VISIT(Visit_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS TEST (
  Test_ID INT PRIMARY KEY,
  Test_Name VARCHAR(100) NOT NULL,
  Result TEXT,
  Visit_ID INT NOT NULL,
  FOREIGN KEY (Visit_ID) REFERENCES VISIT(Visit_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRESCRIPTION (
  Prescription_ID INT PRIMARY KEY,
  Dosage VARCHAR(100),
  Duration VARCHAR(50),
  Visit_ID INT NOT NULL,
  FOREIGN KEY (Visit_ID) REFERENCES VISIT(Visit_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PRESCRIPTION_MEDICINE (
  Prescription_ID INT NOT NULL,
  Medicines VARCHAR(100) NOT NULL,
  PRIMARY KEY (Prescription_ID, Medicines),
  FOREIGN KEY (Prescription_ID) REFERENCES PRESCRIPTION(Prescription_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ASSISTS (
  Nurse_ID INT NOT NULL,
  Visit_ID INT NOT NULL,
  PRIMARY KEY (Nurse_ID, Visit_ID),
  FOREIGN KEY (Visit_ID) REFERENCES VISIT(Visit_ID) ON DELETE CASCADE
);

INSERT INTO DOCTOR (Doctor_ID, Name, Specialty, Contact) VALUES
(1, 'Dr. Asha Rao', 'General Medicine', '9876543210')
ON DUPLICATE KEY UPDATE Name=VALUES(Name);

INSERT INTO CLINIC (Clinic_ID, Clinic_Name, Location) VALUES
(1, 'Rural Care Center', 'Mysuru')
ON DUPLICATE KEY UPDATE Clinic_Name=VALUES(Clinic_Name);

INSERT INTO PATIENT (Patient_ID, Name, Gender, DOB, Age, Blood_Group, Address, City, State) VALUES
(1, 'Sundar Kumar', 'Male', '1988-05-12', 38, 'O+', '1st Cross, Village Road', 'Mysuru', 'Karnataka')
ON DUPLICATE KEY UPDATE Name=VALUES(Name);
